vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO hesphoros/UniConv
    REF "v${VERSION}"
    SHA512 81E290B880E30A14DE218797005B0AD7B6D2D3BCF46B6524FC7DE96DDFB1FCF202F13D20E4714D8A8270759D00D3C19B61D1FED133220AFF9394FC4E60DA699D
    HEAD_REF main
)

string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "dynamic" UNICONV_BUILD_SHARED)

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DUNICONV_BUILD_SHARED=${UNICONV_BUILD_SHARED}
        -DUNICONV_BUILD_TESTS=OFF
        -DUNICONV_LIBICONV_SOURCE=SYSTEM
        -DCMAKE_DISABLE_FIND_PACKAGE_Git=ON
)

vcpkg_cmake_build()
vcpkg_cmake_install()

vcpkg_cmake_config_fixup(
    PACKAGE_NAME UniConv
    CONFIG_PATH lib/cmake/UniConv
)

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")

vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")
